version: '3.1'
services:
  db:
    container_name: my_hci_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_hci_db
    ports:
      - "5432:5432"